package com.leadflow.backend.multitenancy.service;

import com.leadflow.backend.entities.Tenant;
import com.leadflow.backend.repository.tenant.TenantRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.util.Optional;
import java.util.UUID;

/**
 * TenantService — Pure UUID-based tenant management
 *
 * Responsibilities:
 * - Create tenants identified by UUID
 * - Retrieve tenants by UUID or name
 * - Manage tenant lifecycle (soft delete, rename)
 *
 * Architecture:
 * - ALL tenants in 'public' schema
 * - Isolation via tenant_id column (UUID)
 * - NO schema-based isolation
 * - NO per-tenant migrations
 */
@Service
public class TenantService {

    private final TenantRepository tenantRepository;
    private static final Logger logger = LoggerFactory.getLogger(TenantService.class);

    public TenantService(TenantRepository tenantRepository) {
        this.tenantRepository = tenantRepository;
    }

    /* ======================================================
       CREATE TENANT (UUID-BASED)
       ====================================================== */

    /**
     * Create a new tenant with the given name.
     * UUID is auto-generated by Hibernat.
     *
     * @param name tenant name (displayed name, not identifier)
     * @return saved Tenant entity with generated UUID
     * @throws IllegalArgumentException if name is invalid
     */
    public Tenant createTenant(String name) {
        if (name == null || name.isBlank()) {
            throw new IllegalArgumentException("Tenant name cannot be blank");
        }

        Tenant tenant = new Tenant(name);
        Tenant savedTenant = tenantRepository.saveAndFlush(tenant);
        
        logger.info("✅ Tenant created: id={}, name={}", savedTenant.getId(), name);
        
        return savedTenant;
    }

    /* ======================================================
       RETRIEVE TENANT BY ID (UUID)
       ====================================================== */

    /**
     * Retrieve an active tenant by its UUID.
     *
     * @param tenantId tenant UUID identifier
     * @return Optional containing tenant if found and not deleted
     */
    public Optional<Tenant> findById(UUID tenantId) {
        if (tenantId == null) {
            return Optional.empty();
        }
        return tenantRepository.findByIdAndDeletedAtIsNull(tenantId);
    }

    /**
     * Retrieve an active tenant by its UUID, throwing exception if not found.
     *
     * @param tenantId tenant UUID identifier
     * @return active Tenant entity
     * @throws IllegalArgumentException if tenant not found or is deleted
     */
    public Tenant getById(UUID tenantId) {
        return findById(tenantId)
                .orElseThrow(() -> new IllegalArgumentException("Tenant not found: " + tenantId));
    }

    /* ======================================================
       RETRIEVE TENANT BY NAME
       ====================================================== */

    /**
     * Retrieve an active tenant by its name.
     *
     * @param name tenant name
     * @return Optional containing tenant if found and not deleted
     */
    public Optional<Tenant> findByName(String name) {
        if (name == null || name.isBlank()) {
            return Optional.empty();
        }
        return tenantRepository.findByNameIgnoreCaseAndDeletedAtIsNull(name);
    }

    /* ======================================================
       RENAME TENANT
       ====================================================== */

    /**
     * Rename an active tenant.
     *
     * @param tenantId tenant UUID identifier
     * @param newName new tenant name
     * @throws IllegalArgumentException if tenant not found
     */
    public void renameTenant(UUID tenantId, String newName) {
        Tenant tenant = getById(tenantId);
        tenant.rename(newName);
        tenantRepository.saveAndFlush(tenant);
        logger.info("✅ Tenant renamed successfully: new_name={}", newName);
    }

    /* ======================================================
       SOFT DELETE TENANT
       ====================================================== */

    /**
     * Soft-delete an active tenant (mark as deleted).
     *
     * @param tenantId tenant UUID identifier
     * @throws IllegalArgumentException if tenant not found
     */
    public void deleteTenant(UUID tenantId) {
        Tenant tenant = getById(tenantId);
        tenant.softDelete();
        tenantRepository.saveAndFlush(tenant);
        logger.info("✅ Tenant soft-deleted successfully");
    }
}