spring:
  jpa:
    show-sql: false

logging:
  level:
    root: WARN
    com.leadflow: INFO

server:
  port: 8443
  servlet:
    context-path: /api
  ssl:
    enabled: true
    key-store: ${SSL_KEYSTORE_PATH}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
