spring:
  datasource:
    url: jdbc:postgresql://localhost:2411/leadflow_test
    username: postgres
    password: venusia
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      auto-commit: false

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none   # 🔥 Flyway gerencia schema, não Hibernate
    properties:
      hibernate:
        format_sql: true
        multiTenancy: SCHEMA
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    default-schema: public
    locations:
      - classpath:db/migration
    clean-disabled: false

multitenancy:
  enabled: true

logging:
  level:
    root: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.test.context: INFO