# Development Profile - Stripe Configuration
stripe.api.secret-key=sk_test_51TEG1fFzdxPQXW4wPJZ44ulOz2mqrMaPGUpKSJd5toTddkfCTpjQTjOExwuph9uMJhYFFn3PErOLZesj5SSvRryc00ryq0MEU7
stripe.api.publishable-key=pk_test_51TEG1fFzdxPQXW4werLnbwdxt1EGS22nG0PhmbqLGHRsWhaQrQUrNfuqu7bgeZ8rAKP3E0DPEyJX6M1FaXTpVj0c00NFzZaqG2
stripe.webhook.secret=whsec_test_xxxxx
