ALTER TABLE vendors
    ADD COLUMN IF NOT EXISTS last_payment_at TIMESTAMP;

CREATE TABLE IF NOT EXISTS webhook_events (
    event_id VARCHAR(255) PRIMARY KEY,
    received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
