-- Roles
CREATE TABLE roles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Users
CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_users_role FOREIGN KEY (role_id)
        REFERENCES roles(id)
);

-- Leads
CREATE TABLE leads (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phone VARCHAR(15),
    status VARCHAR(50) NOT NULL DEFAULT 'new',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT chk_lead_status
        CHECK (status IN ('new', 'contacted', 'closed'))
);

-- Settings
CREATE TABLE settings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vendor_name VARCHAR(100) NOT NULL,
    whatsapp VARCHAR(15) NOT NULL,
    company_name VARCHAR(100),
    logo TEXT,
    welcome_message TEXT,
    user_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_settings_user FOREIGN KEY (user_id)
        REFERENCES users(id)
);

-- Logs
CREATE TABLE logs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT,
    action TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_logs_user FOREIGN KEY (user_id)
        REFERENCES users(id)
);

-- Lead status history
CREATE TABLE lead_status_history (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    lead_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    changed_by BIGINT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_lsh_status
        CHECK (status IN ('new', 'contacted', 'closed')),
    CONSTRAINT fk_lsh_lead FOREIGN KEY (lead_id)
        REFERENCES leads(id),
    CONSTRAINT fk_lsh_user FOREIGN KEY (changed_by)
        REFERENCES users(id)
);

-- Indexes
CREATE INDEX idx_leads_email ON leads (email);
CREATE INDEX idx_lsh_lead_id ON lead_status_history (lead_id);
CREATE INDEX idx_settings_user ON settings (user_id);
