/* ======================================================
   ROLES
   ====================================================== */

CREATE TABLE roles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


/* ======================================================
   USERS
   ====================================================== */

CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_users_role
        FOREIGN KEY (role_id)
        REFERENCES roles(id)
        ON DELETE RESTRICT
);

/* Unique apenas para usuários ativos */
CREATE UNIQUE INDEX uq_users_email_active
ON users (LOWER(email))
WHERE deleted_at IS NULL;


/* ======================================================
   LEADS
   ====================================================== */

CREATE TABLE leads (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    status VARCHAR(50) NOT NULL DEFAULT 'NEW',
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,

    CONSTRAINT chk_lead_status
        CHECK (status IN ('NEW', 'CONTACTED', 'QUALIFIED', 'CLOSED')),

    CONSTRAINT fk_leads_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

/* Unique por usuário apenas se ativo */
CREATE UNIQUE INDEX uq_lead_email_user_active
ON leads (LOWER(email), user_id)
WHERE deleted_at IS NULL;


/* ======================================================
   LEAD STATUS HISTORY
   ====================================================== */

CREATE TABLE lead_status_history (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    lead_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed_by BIGINT,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_lsh_status
        CHECK (status IN ('NEW', 'CONTACTED', 'QUALIFIED', 'CLOSED')),

    CONSTRAINT fk_lsh_lead
        FOREIGN KEY (lead_id)
        REFERENCES leads(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_lsh_user
        FOREIGN KEY (changed_by)
        REFERENCES users(id)
        ON DELETE SET NULL
);


/* ======================================================
   SETTINGS (1:1 por usuário)
   ====================================================== */

CREATE TABLE settings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vendor_name VARCHAR(100) NOT NULL,
    whatsapp VARCHAR(20) NOT NULL,
    company_name VARCHAR(100),
    logo TEXT,
    welcome_message TEXT,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,

    CONSTRAINT fk_settings_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

/* Garante apenas uma configuração ativa por usuário */
CREATE UNIQUE INDEX uq_settings_user_active
ON settings (user_id)
WHERE deleted_at IS NULL;


/* ======================================================
   LOGS (append-only)
   ====================================================== */

CREATE TABLE logs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT,
    action TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_logs_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE SET NULL
);


/* ======================================================
   PERFORMANCE INDEXES
   ====================================================== */

/* Leads */
CREATE INDEX idx_leads_user_deleted
ON leads (user_id, deleted_at);

CREATE INDEX idx_leads_status_deleted
ON leads (status, deleted_at);

CREATE INDEX idx_leads_email
ON leads (LOWER(email));

/* Lead history */
CREATE INDEX idx_lsh_lead_id
ON lead_status_history (lead_id);

CREATE INDEX idx_lsh_changed_at
ON lead_status_history (changed_at DESC);

/* Settings */
CREATE INDEX idx_settings_user
ON settings (user_id);

/* Logs */
CREATE INDEX idx_logs_user_created
ON logs (user_id, created_at DESC);

CREATE INDEX idx_logs_created_at
ON logs (created_at DESC);
